{{- if and .Values.pi.enabled .Values.pi.sharing.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nebari-pi-pack.fullname" . }}-pi-sharing-hub-exec
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nebari-pi-pack.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nebari-pi-pack.fullname" . }}-pi-sharing-hub-exec
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nebari-pi-pack.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: hub
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nebari-pi-pack.fullname" . }}-pi-sharing-hub-exec
{{- end }}
