{{- if .Values.pi.m4Tools.createTokenSecret }}
{{- $secretName := include "nebari-pi-pack.pi-secret-name" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nebari-pi-pack.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false,Replace=false
type: Opaque
stringData:
  {{- if and $existingSecret (hasKey $existingSecret.data "api-token") }}
  api-token: {{ index $existingSecret.data "api-token" | b64dec | quote }}
  {{- else }}
  api-token: {{ randAlphaNum 64 | quote }}
  {{- end }}
{{- end }}
