{{- if and .Values.pi.enabled .Values.relay.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.relay.core.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nebari-pi-pack.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.relay.core.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nebari-pi-pack.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.relay.core.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nebari-pi-pack.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.relay.core.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.relay.core.serviceAccountName }}
{{- end }}
